<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Felix Li, Gurman Gill, Dia Zavery, Steve He">

<title>Predicting Wine Quality: Insights from Physicochemical Properties 🍷</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="wine_files/libs/clipboard/clipboard.min.js"></script>
<script src="wine_files/libs/quarto-html/quarto.js"></script>
<script src="wine_files/libs/quarto-html/popper.min.js"></script>
<script src="wine_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="wine_files/libs/quarto-html/anchor.min.js"></script>
<link href="wine_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="wine_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="wine_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="wine_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="wine_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary"><strong>1. Summary</strong></a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><strong>2. Introduction</strong></a></li>
  <li><a href="#methods-and-results" id="toc-methods-and-results" class="nav-link" data-scroll-target="#methods-and-results"><strong>3. Methods and Results</strong></a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><strong>4. Discussion</strong></a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="wine.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Wine Quality: Insights from Physicochemical Properties 🍷</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Felix Li, Gurman Gill, Dia Zavery, Steve He </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><strong>1. Summary</strong></h2>
<p>This analysis project attempted to explore the predictive relationships between the physicochemical properties of wine and its quality, utilizing regression analysis and a forward selection algorithm to identify key predictors. Our investigation was motivated by the wine industry’s increasing reliance on data analysis and machine learning to enhance wine quality assessments, aiming to decode the complex interplay between a wine’s chemical makeup and its sensory appeal. Despite the sophisticated methodology and the comprehensive dataset from the UCI Machine Learning Repository <span class="citation" data-cites="cortez2009wine">(<a href="#ref-cortez2009wine" role="doc-biblioref">Cortez et al. 2009</a>)</span>, our findings revealed the model’s limited predictive capability, with a low R-squared value highlighting a significant portion of unexplained variability in wine quality. This outcome, while not entirely unexpected given the nuanced nature of wine quality determination, shows the limitations of linear regression models in capturing the intricate factors that influence wine quality. The analysis points to potential areas for improvement, such as incorporating more or better-quality data, considering additional variables, and employing more complex modeling techniques. Our study thus not only contributes to the academic discourse on predictive modeling in the wine industry but also sets the stage for future research that could leverage advanced analytics to unravel the complexities of wine quality assessment, supporting the industry’s pursuit of excellence and innovation in wine production and evaluation.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction"><strong>2. Introduction</strong></h2>
<p>Wine has been a symbol of culture and refinement throughout human history, with its production dating back thousands of years. The complexity of wine, influenced by its physicochemical properties <span class="citation" data-cites="jjbuckley2018factors">(<a href="#ref-jjbuckley2018factors" role="doc-biblioref">JJ Buckley Fine Wines 2018</a>)</span>, has fascinated scientists and winemakers alike. In recent years, the wine industry has increasingly turned to data analysis and machine learning to understand and predict wine quality. This scientific approach aims to decode the relationship between the chemical composition of wine and its quality as perceived by consumers.</p>
<p>In this project, our primary goal was to determine the best regression model for predicting wine quality and to identify which factors most effectively predict it. The quality of wine is a subject of interest for both enthusiasts and professionals in the field, as it can vary significantly based on a variety of measurable physicochemical properties. By applying regression analysis, we aimed to uncover the relationships between these properties and wine quality, thereby providing a predictive model that could be useful for winemakers and consumers alike. Our research question was formulated as follows: <strong>“What is the best regression model to predict wine quality?”</strong></p>
<p>To address this question, we utilized a dataset that comes from the UCI Machine Learning Repository <span class="citation" data-cites="cortez2009wine">(<a href="#ref-cortez2009wine" role="doc-biblioref">Cortez et al. 2009</a>)</span>, featuring two datasets related to red and white variants of the Portuguese “Vinho Verde” wine. These datasets include 4,898 instances, with 11 features covering various physicochemical properties (such as acidity, sugar level, alcohol content) and 1 output variable representing sensory quality ratings on a scale. The datasets present an opportunity for both classification and regression analyses to model wine quality based on these properties.</p>
<p>Our approach involved conducting a comprehensive analysis to explore the relationships between the physicochemical attributes and the quality scores. Through the use of regression analysis and the implementation of a forward selection algorithm, we aimed to identify the most significant predictors of wine quality. This process allowed us to not only pinpoint the factors that have the most substantial impact on quality but also to determine the most accurate regression model for predicting the quality scores of wine based on its properties.</p>
</section>
<section id="methods-and-results" class="level2">
<h2 class="anchored" data-anchor-id="methods-and-results"><strong>3. Methods and Results</strong></h2>
<section id="data-cleaning-and-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-wrangling">3.1 Data Cleaning and Wrangling</h3>
<div id="5e6e8ed2" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>
The downloaded binary packages are in
    /var/folders/k9/qkhqzgnj1b7cpy3y24kcm4rw0000gn/T//RtmpVfXoG5/downloaded_packages

The downloaded binary packages are in
    /var/folders/k9/qkhqzgnj1b7cpy3y24kcm4rw0000gn/T//RtmpVfXoG5/downloaded_packages

The downloaded binary packages are in
    /var/folders/k9/qkhqzgnj1b7cpy3y24kcm4rw0000gn/T//RtmpVfXoG5/downloaded_packages

The downloaded binary packages are in
    /var/folders/k9/qkhqzgnj1b7cpy3y24kcm4rw0000gn/T//RtmpVfXoG5/downloaded_packages</code></pre>
</div>
</div>
<div id="0fcfef59" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="4">
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>'3'</li><li>'4'</li><li>'5'</li><li>'6'</li><li>'7'</li><li>'8'</li></ol>
</div>
</div>
</section>
<section id="exploratory-data-analysis-eda" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-eda">3.2 Exploratory data analysis (EDA)</h3>
<div id="cell-fig-winedist" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-winedist" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-winedist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wine_files/figure-html/fig-winedist-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-winedist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of Wine Quality
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-facetwine" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-facetwine" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-facetwine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wine_files/figure-html/fig-facetwine-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-facetwine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scatter plots of Wine Quality against Physiochemical Properties
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-facetcorr" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-facetcorr" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-facetcorr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wine_files/figure-html/fig-facetcorr-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-facetcorr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Correlation between pairs of variables in the Wine dataset
</figcaption>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-facetcorr" class="quarto-xref">Figure&nbsp;3</a> above, we notice that there are some variables that has high correlation with others: - citric.acid and fixed acidity - PH and citric.acid - density and fixed acidity - free.sulfur.dioxide and total.sulfur.dioxide</p>
<p>In order to prevent multicollinearity, we decide to remove citric.acid, density and free.sulfur.dioxide</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="9">
<div id="tbl-newdata" class="cell quarto-float anchored" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-newdata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Modified Table with Selected Variables
</figcaption>
<div aria-describedby="tbl-newdata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<table class="dataframe do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 × 9</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">fixed.acidity</th>
<th data-quarto-table-cell-role="th" scope="col">volatile.acidity</th>
<th data-quarto-table-cell-role="th" scope="col">residual.sugar</th>
<th data-quarto-table-cell-role="th" scope="col">chlorides</th>
<th data-quarto-table-cell-role="th" scope="col">total.sulfur.dioxide</th>
<th data-quarto-table-cell-role="th" scope="col">pH</th>
<th data-quarto-table-cell-role="th" scope="col">sulphates</th>
<th data-quarto-table-cell-role="th" scope="col">alcohol</th>
<th data-quarto-table-cell-role="th" scope="col">quality</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>7.4</td>
<td>0.70</td>
<td>1.9</td>
<td>0.076</td>
<td>34</td>
<td>3.51</td>
<td>0.56</td>
<td>9.4</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>7.8</td>
<td>0.88</td>
<td>2.6</td>
<td>0.098</td>
<td>67</td>
<td>3.20</td>
<td>0.68</td>
<td>9.8</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>7.8</td>
<td>0.76</td>
<td>2.3</td>
<td>0.092</td>
<td>54</td>
<td>3.26</td>
<td>0.65</td>
<td>9.8</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>11.2</td>
<td>0.28</td>
<td>1.9</td>
<td>0.075</td>
<td>60</td>
<td>3.16</td>
<td>0.58</td>
<td>9.8</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>7.4</td>
<td>0.70</td>
<td>1.9</td>
<td>0.076</td>
<td>34</td>
<td>3.51</td>
<td>0.56</td>
<td>9.4</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>7.4</td>
<td>0.66</td>
<td>1.8</td>
<td>0.075</td>
<td>40</td>
<td>3.51</td>
<td>0.56</td>
<td>9.4</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method"><strong>3.3 Method</strong></h3>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="10">
<div id="tbl-splitdata" class="cell quarto-float anchored" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-splitdata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Training data
</figcaption>
<div aria-describedby="tbl-splitdata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<table class="dataframe do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 × 9</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">fixed.acidity</th>
<th data-quarto-table-cell-role="th" scope="col">volatile.acidity</th>
<th data-quarto-table-cell-role="th" scope="col">residual.sugar</th>
<th data-quarto-table-cell-role="th" scope="col">chlorides</th>
<th data-quarto-table-cell-role="th" scope="col">total.sulfur.dioxide</th>
<th data-quarto-table-cell-role="th" scope="col">pH</th>
<th data-quarto-table-cell-role="th" scope="col">sulphates</th>
<th data-quarto-table-cell-role="th" scope="col">alcohol</th>
<th data-quarto-table-cell-role="th" scope="col">quality</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>10.4</td>
<td>0.44</td>
<td>6.55</td>
<td>0.074</td>
<td>76</td>
<td>3.17</td>
<td>0.85</td>
<td>12.0</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>6.8</td>
<td>0.83</td>
<td>1.80</td>
<td>0.074</td>
<td>25</td>
<td>3.38</td>
<td>0.45</td>
<td>9.6</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>12.2</td>
<td>0.45</td>
<td>1.40</td>
<td>0.075</td>
<td>6</td>
<td>3.13</td>
<td>0.63</td>
<td>10.4</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>6.8</td>
<td>0.36</td>
<td>1.80</td>
<td>0.067</td>
<td>8</td>
<td>3.36</td>
<td>0.55</td>
<td>12.8</td>
<td>7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>8.4</td>
<td>0.36</td>
<td>2.20</td>
<td>0.081</td>
<td>79</td>
<td>3.30</td>
<td>0.72</td>
<td>11.0</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>8.7</td>
<td>0.82</td>
<td>1.20</td>
<td>0.070</td>
<td>48</td>
<td>3.20</td>
<td>0.58</td>
<td>9.8</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In order to select the best LR model, we will use forward selection because it enables a more efficient selection process than a process such as backward selection. To begin, we will split our data into training data as you can see from <a href="#tbl-splitdata" class="quarto-xref">Table&nbsp;2</a> and testing data. To apply forward stepwise selection, we will start with the intercept-only model, select and add variables sequentially, and finally select the best model of the p models, where p = number of predictor variables. The “best” model can be defined by metrics such as the test MSE which can be revealed with Cp or BIC or adjusted <span class="math inline">\(R^2\)</span> for predictive model selection. Specifically, we can look for the model with biggest adjusted <span class="math inline">\(R^2\)</span>, which indicates a stronger out-of-sample prediction accuracy.</p>
<p>We will obtain 8 possible models obtained using forward selection method.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="12">
<div id="tbl-summaryfsa" class="cell quarto-float anchored" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="12">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summaryfsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary of Forward Selection Algorithm Results
</figcaption>
<div aria-describedby="tbl-summaryfsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<table class="dataframe do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A tibble: 8 × 4</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">n_input_variables</th>
<th data-quarto-table-cell-role="th" scope="col">RSQ</th>
<th data-quarto-table-cell-role="th" scope="col">RSS</th>
<th data-quarto-table-cell-role="th" scope="col">ADJ.R2</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.2625017</td>
<td>443.6771</td>
<td>0.2617311</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.3429754</td>
<td>395.2643</td>
<td>0.3416009</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.3584219</td>
<td>385.9718</td>
<td>0.3564065</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.3635412</td>
<td>382.8920</td>
<td>0.3608726</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.3692863</td>
<td>379.4358</td>
<td>0.3659772</td>
</tr>
<tr class="even">
<td>6</td>
<td>0.3715254</td>
<td>378.0887</td>
<td>0.3675644</td>
</tr>
<tr class="odd">
<td>7</td>
<td>0.3723643</td>
<td>377.5841</td>
<td>0.3677445</td>
</tr>
<tr class="even">
<td>8</td>
<td>0.3727042</td>
<td>377.3796</td>
<td>0.3674217</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>From <a href="#tbl-summaryfsa" class="quarto-xref">Table&nbsp;3</a>, the adjusted <span class="math inline">\(R^2\)</span> will start decreasing after 14 variables are selected. Hence we will be using the model with 7 variables which you can find below.</p>
<div id="ee863196" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>'volatile.acidity'</li><li>'residual.sugar'</li><li>'chlorides'</li><li>'total.sulfur.dioxide'</li><li>'pH'</li><li>'sulphates'</li><li>'alcohol'</li></ol>
</div>
</div>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="16">
<div id="tbl-predictionquality" class="cell quarto-float anchored" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="16">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-predictionquality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Predicted vs.&nbsp;Actual Quality of Wine
</figcaption>
<div aria-describedby="tbl-predictionquality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<table class="dataframe do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 × 2</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">predictedQuality</th>
<th data-quarto-table-cell-role="th" scope="col">quality</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>5.034839</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>5.067650</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>5.267518</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>5.277228</td>
<td>7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>5.745658</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>5.818305</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="17">
<div id="tbl-predictionmetrics" class="cell quarto-float anchored" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="17">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-predictionmetrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Model Evaluation Metrics
</figcaption>
<div aria-describedby="tbl-predictionmetrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<table class="dataframe do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A tibble: 3 × 3</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">.metric</th>
<th data-quarto-table-cell-role="th" scope="col">.estimator</th>
<th data-quarto-table-cell-role="th" scope="col">.estimate</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rmse</td>
<td>standard</td>
<td>1.0955105</td>
</tr>
<tr class="even">
<td>rsq</td>
<td>standard</td>
<td>0.0491032</td>
</tr>
<tr class="odd">
<td>mae</td>
<td>standard</td>
<td>0.8536178</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-fig-scatter" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="18">
<div class="cell-output cell-output-display">
<div id="fig-scatter" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wine_files/figure-html/fig-scatter-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Scatter Plot of Actual vs.&nbsp;Predicted Wine Quality
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion"><strong>4. Discussion</strong></h2>
<section id="summary-and-expectations" class="level3">
<h3 class="anchored" data-anchor-id="summary-and-expectations">4.1. Summary and Expectations</h3>
<p>The analysis employed regression analysis and a forward selection algorithm to identify key predictors of wine quality. The process began with splitting the data into training and testing sets, followed by applying forward stepwise selection to sequentially add variables and select the best model based on metrics such as adjusted R², indicating out-of-sample prediction accuracy. This method aimed to pinpoint the most significant factors affecting wine quality and determine the most accurate regression model for predicting quality scores based on wine properties. The results from the model suggest that it has limited predictive power. The R-squared value as shown in <a href="#tbl-predictionmetrics" class="quarto-xref">Table&nbsp;5</a> indicates that only about 4.9% of the variability in wine quality can be explained by the model, which is quite low. This means that there’s a lot of unexplained variability, and the model might not be capturing all the factors that influence wine quality. The root mean square error (rmse) of around 1.096 and the mean absolute error (mae) of approximately 0.854 indicate that on average, the model’s predictions deviate from the actual quality values by about one point on the quality scale. These metrics together suggest the model’s predictions are not very accurate and there’s substantial room for improvement. The outcome of the regression plot suggests that the model does not perform as well as expected, especially at the higher end of the actual quality scores. The model seems to underestimate the quality of higher-quality wines and overestimate the quality of lower-quality wines. This could indicate that the model’s assumptions or the linearity of the predictors do not hold across the entire range of the quality scores. This may be due to several reasons:</p>
<p><strong>Model Complexity</strong>: The model might be too simple (underfitting), not capturing the complex relationships between predictors and wine quality.</p>
<p><strong>Predictor Selection</strong>: The forward selection algorithm may not have included all relevant predictors, or it may have included irrelevant or noisy predictors.</p>
<p><strong>Data Quality and Quantity</strong>: If the data has errors, outliers, or there’s not enough data, the model’s predictions can be affected. The dataset may also be imbalanced with respect to the quality scores, affecting prediction for underrepresented scores.</p>
<p><strong>Non-linear Relationships</strong>: The relationship between predictors and response may be non-linear or might involve interactions that the linear model does not capture.</p>
<p>In summary the low R-squared could have been expected given the complex nature of wine quality assessment, which is influenced by numerous subtle factors that may not be captured by the model. Improving the model would likely involve incorporating more or better-quality data, considering additional variables, and possibly using more complex modeling techniques that can handle the interplay of factors affecting wine quality.</p>
</section>
<section id="impact-and-future-questions" class="level3">
<h3 class="anchored" data-anchor-id="impact-and-future-questions">4.2. Impact and Future Questions</h3>
<p><strong>Impact:</strong> The implications of this analysis extend beyond its immediate academic context, shedding light on the inherent complexities of predicting wine quality through quantitative models. Despite the model’s limited predictive power, as evidenced by a low R-squared value and substantial prediction errors as seen in <a href="#tbl-predictionmetrics" class="quarto-xref">Table&nbsp;5</a> and <a href="#tbl-predictionquality" class="quarto-xref">Table&nbsp;4</a>, this analysis shows the multifaceted nature of wine quality assessment, which is influenced by a myriad of subtle factors not easily quantifiable. From a practical standpoint, the study highlights the challenges faced by quality assessors in standardizing wine quality metrics, suggesting that reliance on quantitative models alone may not suffice for capturing the nuanced essence of wine quality. Moreover, the findings advocate for a more holistic approach in wine quality evaluation, one that perhaps integrates both objective measurements and subjective expertise. For the wine industry, embracing such complexities and exploring advanced modeling techniques could pave the way for more nuanced quality assessment methods, potentially leading to improved product differentiation and marketing strategies. Ultimately, this analysis serves as a stepping point for future research aimed at refining the predictive accuracy of wine quality models, encouraging a multidisciplinary approach that encompasses sensory analysis, chemistry, and consumer preferences to better understand the determinants of wine quality.</p>
<p><strong>Future Questions:</strong> Building on our initial analysis, future research could explore the impact of environmental changes like climate on the physicochemical composition of wine, delve into the genetic factors influencing grape quality, and employ advanced machine learning algorithms to uncover complex relationships between wine characteristics and sensory perceptions. Specifically, alternative data analysis methods such as deep learning and neural networks <span class="citation" data-cites="pascua2023combined">(<a href="#ref-pascua2023combined" role="doc-biblioref">Pascua et al. 2023</a>)</span> could be employed to analyze large datasets more effectively, identifying non-linear relationships and subtle patterns that traditional statistical methods may miss. Additionally, integrating big data analytics to process and analyze the vast amount of data generated from different wine regions could offer unprecedented insights into regional and varietal influences on wine quality. Investigating alternative fermentation techniques and conducting comparative studies across different wine regions could reveal new insights into optimizing wine quality. These efforts should embrace interdisciplinary approaches, combining advanced data analysis, biotechnology, and sensory evaluation to enhance our understanding of wine quality. Such research would not only deepen our knowledge of the factors affecting wine but also support the industry in adapting to evolving challenges and preferences, ultimately enriching the wine production and selection process.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-cortez2009wine" class="csl-entry" role="listitem">
Cortez, Paulo, A. Cerdeira, F. Almeida, T. Matos, and J. Reis. 2009. <span>“Wine Quality.”</span> <a href="https://archive.ics.uci.edu/ml/datasets/wine+quality">https://archive.ics.uci.edu/ml/datasets/wine+quality</a>.
</div>
<div id="ref-jjbuckley2018factors" class="csl-entry" role="listitem">
JJ Buckley Fine Wines. 2018. <span>“The 4 Factors and 4 Indicators of Wine Quality.”</span> 2018. <a href="https://www.jjbuckley.com/wine-knowledge/blog/the-4-factors-and-4-indicators-of-wine-quality/1009">https://www.jjbuckley.com/wine-knowledge/blog/the-4-factors-and-4-indicators-of-wine-quality/1009</a>.
</div>
<div id="ref-pascua2023combined" class="csl-entry" role="listitem">
Pascua, K. B., H. D. Lagura, G. S. Lumacad, A. K. N. Pensona, and M. J. I. Jalop. 2023. <span>“Combined Synthetic Minority Oversampling Technique and Deep Neural Network for Red Wine Quality Prediction.”</span> In <em>2023 International Conference in Advances in Power, Signal, and Information Technology (APSIT)</em>, 609–14. <a href="https://doi.org/10.1109/APSIT58554.2023.10201733">https://doi.org/10.1109/APSIT58554.2023.10201733</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>